### PR TITLE
Tic-Tac-Toe Unit Test using RSpec

### PR DESCRIPTION
**Pull request by kwizl**
# TDD for Tic-Tac-Toe Project

- This part of the comprises of Unit Test for the Tic-Tac-Toe Project for the Ruby Milestone OOP. It is written using RSpec a tool for writing tests in Ruby. We are testing all possible scenarios of the game.

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Good Job :+1: 
I must say am impressed with the edge cases you covered in this PR. I see you thoroughly thought about most scenarios when testing your code.
However, how do you test when it's a draw or not??
- [ ] add tests for when it's a draw. It should return true
- [ ] what about when it's not a draw? Return false

### Martin Afani

**Comment by codecell** [comment]
Hi @whiz25 , We seriously don't understand what **exactly** you expect  us to do from the feedback you gave us. Because critically looking at our logic_spec.rb file, we guess we extensively covered those cases as can be seen here 
`let(:arrey_9) { [[1, 2, 'X'], [4, 'X', 6], ['X', 8, 9]] }
    it 'Should return TRUE if a win case [3, 5, 7] is met' do
      actual = subject.player_win_cases(player_labelz, arrey_9)
      expect(actual).to be(true)
    end

    let(:player_label_2) { 'X' }
    let(:arrey_2) { [['X', 2, 'X'], [4, 5, 6], [7, 8, 9]] }
    it 'Should return FALSE if a win case is NOT met' do
      actual = subject.player_win_cases(player_label_2, arrey_2)
      expect(actual).to be(false)
    end
  end
`

...And if there is a method or class you think we didn't cover, please refer us to the actual method so we can cover it.
The feedback looks so vague and we're unable to make out what exactly  you expect us to do

**Comment by whiz25** [comment]
@codecell 
I understand what you mean. But enlighten me on how you checking for `draw` in the game.
Checking for `If win case is not met` is vague. There so many cases that can return `true` in this case. For example, if the game is still continuing, it will return `false`. What if the game ends but the win condition is not met? That would be a draw.
I may be wrong about my observation. Could you tell me what method is checking the draw condition?

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, but there is one more thing required. 
- [ ] Lets write test for when there is a draw between ****both players**** 

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by codecell** [comment]
Hi @whiz25  of course there are so many cases that do default  to a draw
, in this case 
`let(:player_label_2) { 'X' }
let(:arrey_2) { [['X', 2, 'X'], [4, 5, 6], [7, 8, 9]] }
it 'Should return FALSE if a win case is NOT met' do
  actual = subject.player_win_cases(player_label_2, arrey_2)
  expect(actual).to be(false)
end`
Here, if a win case is not met, then obviously it will eventually end in a  draw and the method 
player_win_state will equal false, i.e game_on = false and the only time game_on equals false is when the 9 slots are exhausted.
From what I understand about this spec project, it is to test all the classes and methods that we implemented in our project which we guess we covered. Except if there is another way to make Rspec play the game, which we can't possibly think of  right now

**Comment by codecell** [comment]
Hi @kobiyoyo  and @whiz25 our **player_win_cases(player_label, array)** method returns either 
**true -- if a win case is met**
or 
**false -- if a win case is not met** which is DRAW
and we tested all the win cases and also the Draw cases  which is anytime player_win_cases returns false, We tested it here 
`it 'Should return FALSE if a win case is NOT met' do
 actual = subject.player_win_cases(player_label_2, arrey_2) 
expect(actual).to be(false) end`

image

Please you people should take time and look the code

**Review by kobiyoyo — APPROVED** [review]
# Project Approved :thumbsup:
## Hello Team ,  You have done a great job with this project. :clap:

**Pull request merged**
